all:
	javac Player.java
	javac Pong.java
	javac PongWindow.java
	javac Test.java
	javac SwingControlDemo.java
	java -Djava.net.preferIPv4Stack=true Test 1 1

clean:
	rm Player.class
	rm SendClass.class
	rm Pong.class
	rm PongWindow.class
	rm Test.class
	rm Receiver.class

run:
	java -Djava.net.preferIPv4Stack=true Test 1 1
